TEST_DEVICE=/dev/sdc
XFS_PARTITION=${TEST_DEVICE}3
BTRFS_PARTITION=${TEST_DEVICE}2
EXT4_PARTITION=${TEST_DEVICE}4
XFS_MOUNTPOINT=xfs_drive/
BTRFS_MOUNTPOINT=btrfs_drive/
EXT4_MOUNTPOINT=ext4_drive/
TESTFILE=randomfile
